
#配置数据库文件存储目录以及账户密码和驱动
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.113:3309/parking?characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: 123456
#   initialization-mode: always
#   schema: classpath:db/schema.sql
#   data: classpath:db/data.sql
#   sql-script-encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true  # 显示出Hibernate查询语句的绑定参数值
    properties:
      hibernate:
        format_sql: true

  output:
    ansi:
      enabled: always # always是默认值，但VS Code是不加这个CONSOLE没有颜色


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace


# The secret key using which we will be using for hashing algorithm. The secret 
# key is combined with the header and the payload to create a unique hash. We 
# are only able to verify this hash if you have the secret key.
# jwt:
#   secret: javainuse
